#!/usr/bin/env python3
"""This is a module to authenticate users"""
import bcrypt
from db import DB
from uuid import uuid4 as uid
from sqlalchemy.orm.exc import NoResultFound
from user import User


def _hash_password(password: str) -> bytes:
    """This is a function that hashes password entered by a user

    Args:
        password(str): plaintext password to be hashed

    Returns:
        (bytes) representation of the the hashed and salted password
    """
    return bcrypt.hashpw(password.encode("utf-8"),
                         bcrypt.gensalt())


def _generate_uuid() -> str:
    """This is a function to generate UUID 4 strings

    Returns:
        generated uuid string token
    """
    return str(uid())


class Auth:
    """Auth class to interact with the authentication database.
    """

    def __init__(self):
        self._db = DB()

    def register_user(self, email: str, password: str) -> User:
        """This is a method to register a new user

        Args:
            email(str, required): This is the email of the user to register
            password(str, required): The password of the user to register

        Returns:
            User(obj): User object just registered.
        """
        try:
            self._db.find_user_by(email=email)  # try if user already exists
        except NoResultFound:
            self._db.add_user(email, _hash_password(password))  # add user
        else:
            raise ValueError(f'User {email} already exists')  # raise an error

    def valid_login(self, email: str, password: str) -> bool:
        """This is a method to validate user Login

        Args:
            email(str, required): This is the email of the user to login
            password(str, required): The plaintext password of user to login

        Returns:
            (bool): True if login validated else False
        """
        try:
            user = self._db.find_user_by(email=email)
            pwd = password.encode('utf-8')
            return bcrypt.checkpw(pwd, user.hashed_password)
        except NoResultFound:
            return False

    def create_session(self, email: str) -> str:
        """This is a method to create a session for a validated user

        Args:
            email(str, required): The email of the user to create session for

        Returns:
            (str): The session_id created for the user
        """
        try:
            user = self._db.find_user_by(email=email)
            if user is not None:
                sess_id = _generate_uuid()
                self._db.update_user(user.id, session_id=sess_id)
                return sess_id
        except NoResultFound:
            return None
        return None

    def get_user_from_session_id(self, session_id: str) -> User:
        """This is a method to get a User details from the seesion ID of the
        currently logged in or validated user.

        Args:
            session_id(str, required): The session_id of the currently logged
            in user

        Returns:
            If found return User(obj) else return None
        """
        if session_id is not None:
            try:
                user = self._db.find_user_by(session_id=session_id)
                return user if user is not None else None
            except (NoResultFound, Exception):
                return None
        return None

    def destroy_session(self, user_id: int) -> None:
        """This is a method to destroy the session of the currently validated
        or logged in user and update their session_id attribute

        Args:
            user_id(int, required): The user_id of the currently logged
            in user

        Returns:
            None
        """
        try:
            user = self._db.find_user_by(id=user_id)
            if user is not None and user.id == user_id:
                self._db.update_user(user_id, session_id=None)
        except NoResultFound:
            return None
        return None

    def get_reset_password_token(self, email: str) -> str:
        """This is a method that generates a reset_token UUID for a user
        identified by an email.

        Args:
            email(str): The email address of the user to reset password

        Returns:
            (str): UUID Token generated
        """
        try:
            user = self._db.find_user_by(email=email)
            if user is not None:
                reset_token = _generate_uuid()
                if user.reset_token is None:
                    self._db.update_user(user.id, reset_token=reset_token)
                return reset_token
            else:
                raise ValueError()
        except NoResultFound:
            raise ValueError()

    def update_password(self, reset_token: str, password: str) -> None:
        """This is a function that updates a user's password prior to
        a password reset token generated by the user on request.

        Args:
            reset_token(str, required): Reset token generated
            password(str): new password to store

        Returns:
            None
        """
        try:
            user = self._db.find_user_by(reset_token=reset_token)
            print(dir(user), user.reset_token, user.session_id)
            if user is not None:
                h_pass = _hash_password(password)
                self._db.update_user(user.id,
                                     hashed_password=h_pass,
                                     reset_token=None)
                print(dir(user), user.reset_token, user.session_id)
                return None
            else:
                raise ValueError
        except NoResultFound:
            raise ValueError
